version: '3'

services:
  db:
    image: postgres
    container_name: pg
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: golojadb

    volumes:
      - goloja:/var/lib/postgres
  # TODO: Adiciocar um container para a plicação go

volumes:
  goloja:
